[package]
name = "day_16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.3"

[[bin]]
name="part1"
path="src/part1.rs"

[[bin]]
name="part2"
path="src/part2.rs"
