[package]
name = "day_22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.2"
nalgebra = "0.32.3"

[[bin]]
name="part1"
path="src/part1.rs"

[[bin]]
name="part2"
path="src/part2.rs"
